name: 'parflow_nn'

channels:
  - defaults

dependencies:
  - python=3.8
  - pip
  - configargparse
  - graphviz
  - h5py
  - ipykernel
  - jupyter
  - keras
  - matplotlib
  - netcdf4
  - numpy
  - pydot
  - seaborn
  - tensorflow
  - tqdm
  - xarray
  - pip:
    - cond-rnn
    - fire
    - git+https://github.com/hoangtv1899/pfio.git